export const URLS = {
    sign_in: 'api/auth/sign-in',
    user_list: "/api/users/get-all",
    user_add: "/api/users/add",
    user_edit: "/api/users/edit",
    user_delete: "/api/users/delete",
    get_file: "/api/files/get",
    pharmacy_add: "/api/pharmacy/add",
    doctor_add_visit: "/api/doctor/add-visit",
    doctor_add_agreement: "/api/doctor/add-agreement",
    medicine_list: "/api/medicine/get-all",
    medicine_add: "/api/medicine/add",
    medicine_edit: "/api/medicine/edit",
    medicine_delete: "/api/medicine/delete",
};
